### ISSUE TITLE
the code about the span extraction tree

### ISSUE THREAD

**Issue by yunjuyan** [lfy79001/RegHNT#1]
In your paper,( Appendix C Details of the span extraction question), but I can't find the code related to the span extraction tree, can you specify which file it is in? Thanks!

**Comment by lfy79001** [comment]
Sorry, the current repository does not contain that part of code. The code of span extraction tree is messy, so it hasn't been uploaded. And after many experiments, it has little effect on performance. This paper mainly focus on numerical reasoning questions. Thank you for your attention.

**Comment by yunjuyan** [comment]
已收到
